Optimize action

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -83,6 +83,8 @@ jobs:
       migration_list: ${{ steps.set-tag.outputs.migration_list }}
     env:
       HAS_SSH_KEY: ${{ secrets.BL_GITHUB_SSH_KEY != '' }} 
+      AWS_ENV: ${{ needs.build.outputs.branch == inputs.PRODUCTION_BRANCH && 'PROD' || 'DEV' }}
+
     steps:
 
     - name: Deployment details
@@ -138,13 +140,11 @@ jobs:
         elif [[ ${GITHUB_REF_TYPE} == 'tag' ]]; then
           echo "Git tag detected"
           GIT_BRANCH="${{ inputs.PRODUCTION_BRANCH }}"
-          # GIT_TAG=${{github.ref_name}}
           deploy_type="docker image build"
         else
           echo "Git branch detected"
           # If branch name is feature/myfeature, only extract "myfeature"
-          GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | awk -F'/' '{ print $NF}')
-          # GIT_TAG=$(echo ${GITHUB_REF#refs/heads/} | awk -F'/' '{ print $NF}')
+          GIT_BRANCH=$(basename "$GITHUB_REF")
           deploy_type="deployment"
 
           if [[ $GIT_BRANCH == "${{ inputs.PRODUCTION_BRANCH }}" ]]; then
@@ -154,11 +154,10 @@ jobs:
         fi
 
 
-        MICROSERVICE_SHORT_NAME=$(echo ${MICROSERVICE} | awk -F'service-' '{ print $NF}')
+        MICROSERVICE_SHORT_NAME="${MICROSERVICE#service-}"
 
         # test if there were changes in DB migrations
-        migrationList=$(git diff origin/${{ inputs.PRODUCTION_BRANCH }} HEAD --name-only --diff-filter=d | grep migrations/ | awk '{printf "%s\\n", $0}')
-
+        migrationList=$(git diff origin/${{ inputs.PRODUCTION_BRANCH }} HEAD --name-only --diff-filter=d | grep '^migrations/' || true)
 
         echo "GITHUB_REF: ${GITHUB_REF}"
         echo "GIT_BRANCH: ${GIT_BRANCH}"
@@ -181,17 +180,18 @@ jobs:
         fi
         echo "DOCKERFILE = ${DOCKERFILE}"
         
-        echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
-        echo "tag=$GIT_TAG" >> $GITHUB_OUTPUT
-        echo "microservice=$MICROSERVICE" >> $GITHUB_OUTPUT
-        echo "microservice_short_name=$MICROSERVICE_SHORT_NAME" >> $GITHUB_OUTPUT
-        echo "deploy_type=$deploy_type" >> $GITHUB_OUTPUT
-        echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_OUTPUT
-        echo "dockerfile=$DOCKERFILE" >> $GITHUB_OUTPUT
-        # for multi-line output
-        echo "migration_list<<|" >> $GITHUB_OUTPUT
-        echo "$migrationList" >> $GITHUB_OUTPUT
-        echo "|" >> $GITHUB_OUTPUT
+        cat <<EOF >> $GITHUB_OUTPUT
+        branch=$GIT_BRANCH
+        tag=$GIT_TAG
+        microservice=$MICROSERVICE
+        microservice_short_name=$MICROSERVICE_SHORT_NAME
+        deploy_type=$deploy_type
+        ECR_REPOSITORY=$ECR_REPOSITORY
+        dockerfile=$DOCKERFILE
+        migration_list<<|
+        $migrationList
+        |
+        EOF
 
     - uses: kanga333/variable-mapper@master
       with:
@@ -200,10 +200,6 @@ jobs:
         map: |
           {
             "${{ inputs.PRODUCTION_BRANCH }}": {
-              "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID_PROD }}",
-              "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}",
-              "AWS_ROLE_EXTERNAL_ID": "${{ secrets.AWS_ROLE_EXTERNAL_ID_PROD }}",
-              "AWS_ROLE_TO_ASSUME": "${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}",
               "EKS_CLUSTER_NAME": "gek-prd",
               "environment": "production",
               "K8S_NAMESPACE":"worklib",
@@ -219,10 +215,6 @@ jobs:
               "K8S_NAMESPACE":"autotest"
             },
             ".*": {
-              "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID_DEV }}",
-              "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}",
-              "AWS_ROLE_EXTERNAL_ID": "${{ secrets.AWS_ROLE_EXTERNAL_ID_DEV }}",
-              "AWS_ROLE_TO_ASSUME": "${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}",
               "ECR_REPOSITORY": "${{ steps.set-tag.outputs.ECR_REPOSITORY }}",
               "EKS_CLUSTER_NAME": "gek-ppd",
               "environment": "qa",
@@ -257,10 +249,10 @@ jobs:
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
-        aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key:  ${{env.AWS_SECRET_ACCESS_KEY }}
-        role-external-id: ${{ env.AWS_ROLE_EXTERNAL_ID }}
-        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
+        aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID_' + env.AWS_ENV] }}
+        aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY_' + env.AWS_ENV] }}
+        role-external-id: ${{ secrets['AWS_ROLE_EXTERNAL_ID_' + env.AWS_ENV] }}
+        role-to-assume: ${{ secrets['AWS_ROLE_TO_ASSUME_' + env.AWS_ENV] }}
         role-duration-seconds: 1200
         role-skip-session-tagging: true
         aws-region: eu-west-1
@@ -282,26 +274,20 @@ jobs:
     - name: Build, tag and push image using Buildx with cache
       id: build-image-service
       uses: docker/build-push-action@v6
-      if: ( inputs.NEEDS_IMAGE_BUILD == true )
-      env:
-        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
-        IMAGE_TAG: ${{ steps.set-tag.outputs.tag }}
-        NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
-        WORKLIB_GITHUB_SSH_KEY: ${{ secrets.BL_GITHUB_SSH_KEY }}
+      if: inputs.NEEDS_IMAGE_BUILD == true
       with:
         context: .
         file: ./${{ steps.set-tag.outputs.dockerfile }}
 
-        # Push vers ECR
+        # Push to ECR
         push: true
         tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.set-tag.outputs.tag }}
 
         # Cache BuildKit (pnpm + layers)
-        cache-from: type=gha
-        cache-to: type=gha,mode=max
+        cache-from: type=gha,scope=${{ steps.set-tag.outputs.microservice_short_name }}
+        cache-to: type=gha,mode=max,scope=${{ steps.set-tag.outputs.microservice_short_name }}
 
-        # Secrets utilisés dans le Dockerfile
+        # Secrets used in Dockerfile
         secrets: |
           notion_access_token=${{ secrets.NOTION_ACCESS_TOKEN }}
         ssh: ${{ env.HAS_SSH_KEY == 'true' && 'default' || '' }}
@@ -317,50 +303,44 @@ jobs:
         MICROSERVICE: ${{ steps.set-tag.outputs.microservice }}
       if: (steps.set-tag.outputs.branch != inputs.PRODUCTION_BRANCH )&&( inputs.NEEDS_DEPLOY == true )
       run: |
-       if [[ ("${{ env.EKS_CLUSTER_NAME }}" == "gek-prd")||("${{ env.environment }}" == "production") ]]; then
-          echo "Workflow run on ${{ inputs.PRODUCTION_BRANCH }} branch, aborting."
-          exit 1
-       fi
+        if [[ ("${{ env.EKS_CLUSTER_NAME }}" == "gek-prd")||("${{ env.environment }}" == "production") ]]; then
+            echo "Workflow run on ${{ inputs.PRODUCTION_BRANCH }} branch, aborting."
+            exit 1
+        fi
 
-       aws eks update-kubeconfig --name=${{ env.EKS_CLUSTER_NAME }}
+        # set the deploy directory (Frontend apps (not starting with "service-") have their own deploy directory)
+        deploy_dir="deploy/k8s_ci"
+        [[ ! "$MICROSERVICE" =~ ^service- ]] && deploy_dir="$deploy_dir/$MICROSERVICE"
 
-       # set the environment variables
-       deploy_dir="deploy/k8s_ci"
-       # Frontend apps (not starting with "service-") have their own deploy directory
-       if [[ ! "$MICROSERVICE" =~ ^service- ]]; then
-         deploy_dir="$deploy_dir/$MICROSERVICE"
-       fi
-       cd $deploy_dir
-       chmod +x ./replace_parameters.sh
-       ./replace_parameters.sh ${{ env.environment }} "NOTIMPORTANT" $MICROSERVICE_SHORT_NAME $IMAGE_TAG
-       cd -
-       
-       curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.6/bin/linux/amd64/kubectl
-       chmod a+rx kubectl
-       if ${{ inputs.NEEDS_MIGRATION }}; then
-           # delete job to prevent failure if it already exists 
-           ./kubectl delete job job-$MICROSERVICE_SHORT_NAME-migration -n ${{ env.K8S_NAMESPACE }} || echo "job-$MICROSERVICE_SHORT_NAME-migration does not exists, it is ok"
-       fi
+        # Configure kubeconfig
+        aws eks update-kubeconfig --name=${{ env.EKS_CLUSTER_NAME }}
 
-       # Deploy api
-       echo "./kubectl apply -k $deploy_dir/overlays/${{ env.environment }}"
-       ./kubectl apply -k ${deploy_dir}/overlays/${{ env.environment }}
-
-       if ${{ inputs.NEEDS_MIGRATION }}; then
-           # output migration logs
-           kubectl wait --for=condition=complete job/job-$MICROSERVICE_SHORT_NAME-migration --timeout=150s -n ${{ env.K8S_NAMESPACE }} || echo "Timeout error. DB migrations did not fit the timout of 150 sec. It does NOT mean that the deployment is failed, please check the PODs statuses manually"
-           ./kubectl logs job/job-$MICROSERVICE_SHORT_NAME-migration -n ${{ env.K8S_NAMESPACE }}
-
+        # prepare manifest
+        cd $deploy_dir
+        chmod +x ./replace_parameters.sh
+        ./replace_parameters.sh ${{ env.environment }} "NOTIMPORTANT" $MICROSERVICE_SHORT_NAME $IMAGE_TAG
+        cd -
+        
+        # deploy migration function :
+        deploy_migration() {
+            job="job-$MICROSERVICE_SHORT_NAME-migration"
+            ./kubectl delete job $job -n ${{ env.K8S_NAMESPACE }} || echo "$job does not exist"
+            ./kubectl wait --for=condition=complete job/$job --timeout=150s -n ${{ env.K8S_NAMESPACE }} || echo "Timeout error. DB migrations did not fit the timout of 150 sec. It does NOT mean that the deployment is failed, please check the PODs statuses manually"
+            ./kubectl logs job/$job -n ${{ env.K8S_NAMESPACE }}
             echo "check DB migration status";
-            if [ "$(kubectl -n ${{ env.K8S_NAMESPACE }} get jobs job-$MICROSERVICE_SHORT_NAME-migration -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}')" = "True" ]; then 
-              echo "DB migration failed";  
-              exit 1; 
-            fi;
+            if [[ $(./kubectl -n ${{ env.K8S_NAMESPACE }} get jobs $job -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}') == "True" ]]; then
+              echo "DB migration failed"
+              exit 1
+            fi
+        }
 
-       fi
+        # Deploy migrations if necessary
+        ${{ inputs.NEEDS_MIGRATION }} && deploy_migration
 
-       # output deployment status
-       ./kubectl rollout status deployment $MICROSERVICE -n ${{ env.K8S_NAMESPACE }}
+        # Deploy manifest
+        echo "./kubectl apply -k $deploy_dir/overlays/${{ env.environment }}"
+        ./kubectl apply -k ${deploy_dir}/overlays/${{ env.environment }}
+        ./kubectl rollout status deployment $MICROSERVICE -n ${{ env.K8S_NAMESPACE }}
 
   notification:
     needs: build
